### ISSUE TITLE
Muito foddaa manoo

### ISSUE THREAD

**Issue by alissonandrade2020** [Gabrielpdev/Proffy#3]
Queria aprender esse metodo para implementar no meu, me ajuda ????? = ]

**Comment by Gabrielpdev** [comment]
Fala mano, ajudo sim, qual funcionalidade vc esta com duvida ?


Em sex., 7 de ago. de 2020 às 19:31, Alisson de Andrade Araújo <
notifications@github.com> escreveu:

**Comment by alissonandrade2020** [comment]
no caso seria essa de login só pow, essa parte de autenticação

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Gabrielpdev** [comment]
Me chama lá no discord
Gabriel Pereira #1233

Em sex, 7 de ago de 2020 19:54, Alisson de Andrade Araújo <
notifications@github.com> escreveu:
